language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: TtY7rRKynZXjyLjnrEfzqnx6EFvO2n5AFoG+VFpaRGT3B+04EreIFmhEki08IKGkiMTd6BN4DgxvGkqmLRbm98AHXn/Q7V5uh+fqGquwWzQY2mq9lBAYlQDmN5X2tMbak+/hedevU/mKFE9hfilGyi/hUv7tekpRGjlJmkrQ9xLZ3hztWmRuuwnQp1yPvlO7kc2owr40S2JHfG9gdrJ44c781OK2X/gmfhqoTm/KMmaFxi6ouZ1vTbSVqADqQQnp+caTMKhuo18yjfQAgPbb4Upnl1NbTIXnjd+Ab0Hvh5tf7smlfFSxqSjzdG54Pb8prVl3XqKZa9Uby9RlKlCOShUoMiLYCCUy4wVcFlsoft4jXAzRoH7uAG5/BAMJRQ8+sybFANyOPBH41/dsRPgR68P+ifwSqoCsF8vaiIhavcv0p/ALFkwxsbQA9G0uBxqCyeGc/fNQp1PLqeH4YIeIRrYNOJf8/i5LVSFoUr7IGgfKolpebzjPsu6Jn+V75GlOFXRko6YbvT1njeaB0cMJYm5SLGQFTa7Mbk/PyDGkzi1HqmpJaYyeFTEq9vA6lAS3Tf7rWkoWPPvUMe5IGZCZqIOVQ2u8il70upCiZnrycJTFAshsK86FYPzVEwPdU5LNUIeD2N+n2oE0jkFT/BCtc/3L2cbqTfqDS4hZEES4x6o=
  app: smcfio
  on:
    repo: sofiacf/smcfio
