language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: u3n+wr0v9wGpov1fE9WiO7CsDoAcdBM9NB00iv1cccRH36A3lsZ/vpgvb3Sd+FGXlJYhi50s1lQAfNSMdd/a2vJo6G0cyT/hjuOZ1x3+nqeefJFXrjWV0pA4o1x6ZJGY/Ia3iPsqnn0Epsaap/JkWNcw03R3RF16unz8qcU7RWITSyfBVEWTVx9JhW/nsU0zEXpplE9CiiYBzfjZCRBFBX10AxrkJ/uQiTcmWwqNsZjBxRAt6zcXdOPgp5spY7Sd+/u040+j7nSo5n8q82UfBYmyesf7l+3bIPxATPAV2fW/6Oqc65iI4fxYj1RQZmL+O/AjefeKDgl7kjKLyC+FvTE0jNxCkDEbAPZkkTT6W8uIkcs0quqMME4FPiX8Duk1Ijcg5Ke2iwfaaHQuTAQ0NBx/KlOhNKX2Y/5608EiQ0Px19LFSdBURO2YZ7wrridbjZKHa7yl/hwjWfzOWjGeo3nyDRpfQIeGJN+jjqf2HkW2lISenOTeQOSNdFRJFFjCqDlvcfR6gpD2C8o/dQN9e8fIwnTxL0jy9sqboE0h3uiEv6UKHvcuONGPXkhEx9FkjEXTNu6G86GoRuOhOQu2IcYXzIjRcg4CLvSLCPmUfmCeEMtDvfzl/XpvczfQX/4sr3L0XwO1QYHWex+9nzdSMuYgxL4Zz36yEsrjoFEgD0M=
  app: smcfio
  on:
    repo: sofiacf/smcfio
true:
  branch: master
