language: node_js
node_js:
- stable
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: AeHwde1dSkeho6Lfm/vmad9BXhSSw8OFDniVivglSovmh508OALLZ6pMQ5E6cDfeBWYejjwKD7a2g3AYdK5MsfSy+dYy2OQwfmYnOI/0nY4gBPbNU0JcENiATD5Zm1TgJIS1OKDtTqu+u/pHltidMA4iffL1EP9wVu9qCRZfoOyPrmJ/0h/Q9ULIHdLq9pamgQPVqF13HxDgsZZ5FoSxTEy7V5nXcw/iIB21YPgrK7RROiXzpLPiK856Mo3hNfABSZE3T/Kx6KwvkroK+iKMGHQf8oSBuF6+tNwDP5fvUDEaRVC+vO+iwZdIx3nbTKDkm+oj55d+wpvG0Xr0Gxh7Hwm/7x2+yM4MQz/5wSx0CxOY4swYudPhnmyIW+GQQ9SGJV+gSNY/MoPbJh6QJaDfmMsZcKadGpMbj96ljkHd9GlMFXYczU7TBCrEblcQYlao5NuBsAAFpuWLRl+Ww4uSRZJijkH+Y4k4JKxo7n0s7IQWr9zBAhWdF2EuFzYDOIxf0N8PgPTOxyOIroDRp3pfqluriNwy9r8DpARhEaGExWvoKUkNthMW+I0QDlGpSHGSnI0Tndy1vVq9Mbbv3E8RiCOS3jzViJZFodjjRSDOLpx5WIlfChYkWWbqUKGLA3UVC+oKk6NH6K3qiO2BknINmS3pCIG1WcbP1eVqa8e+j78=
  app: smcfio
  on:
    repo: sofiacf/smcfio
