name: test

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Tag name'
        required: true
        default: 'v0.0.1'
        type: string

jobs:
  get-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
